spring:
  application:
    name: prj-friends
  datasource:
    url: jdbc:h2:file:./data/friendsdb;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: never  # schema.sql, data.sql 실행x(파일모드로 db저장)
  main:
    banner-mode: console
  logging:
    config: classpath:log4j2.xml   # log4j2 설정 파일 위치

server:
  port: 8080

